module-name: warden
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/warden/operator:main
  - europe-docker.pkg.dev/kyma-project/prod/warden/admission:main
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
