module-name: warden
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/warden/operator:0.14.0
  - europe-docker.pkg.dev/kyma-project/prod/warden/admission:0.14.0
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
