module-name: warden
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/warden/operator:main
  - europe-docker.pkg.dev/kyma-project/prod/warden/admission:main
mend:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/test/**"
    - "**/*_test.go"
