# Default values for warden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#Service configuration
global:
  operator:
    image: europe-docker.pkg.dev/kyma-project/dev/warden/operator:v20230130-796b77d1

  admission:
    image: europe-docker.pkg.dev/kyma-project/dev/warden/admission:v20230130-796b77d1

  config:
    dir: /workspace
    filename: config.yaml
    configmapName: warden-config
    data:
      notary:
        URL: "https://signing-dev.repositories.cloud.sap"
        timeout: 30s
        # list of comma-separated registries addresses
        allowedRegistries: ""
      admission:
        systemNamespace: "{{ .Release.Namespace }}"
        serviceName: "{{ .Chart.Name }}-admission"
        secretName: "{{ .Chart.Name }}-admission-cert"
        timeout: 2s
        port: 8443
      operator:
        metricsBindAddress: "127.0.0.1:8080"
        healthProbeBindAddress: ":8081"
        leaderElect: true

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
        - ALL


#TODO: group k8s related settings under kubernetes?
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "warden-controller-manager"

podAnnotations: {}

service:
  type: ClusterIP
  port: 8443

resources:
   limits:
     cpu: 256m
     memory: 128Mi
   requests:
     cpu: 20m
     memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

imageRenderer: {}
