name: k3d integration test

on:
  push:
    branches: [ "main", "release-*" ]
  workflow_dispatch:
  pull_request:

jobs:
  k3d-integration-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create Single Cluster
      uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
      with:
        cluster-name: "k3dCluster"
        args: >-
          --agents 1
          --port 80:80@loadbalancer
          --port 443:443@loadbalancer
          --wait
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    - name: run test
      run: make verify-on-cluster
